inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'test/dummies/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/LeadingCommentSpace:
  Exclude:
    - 'lib/generators/cogy/templates/**/**'

#
# Disabled Cops
#
Style/RescueStandardError:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/ClassVars:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Next:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
